### PR TITLE
 Fix #316

### LINKED ISSUE #316: Something wrong with pickups in more than one virtual world
Look at the video: https://youtu.be/TJ51a1erZig

Code:
```Pawn
#include <a_samp>
#include "zcmd"
#include "streamer"

public OnGameModeInit()
{
	CreateDynamicPickupEx(1275, 38, 0.0, 0.0, 4.0, .worlds = {0, 1});
	return 1;
}

CMD:world(playerid, params[])
{
	SetPlayerVirtualWorld(playerid, strval(params));
	return 1;
}

CMD:info(playerid, params[])
{
	new string[144];
	format(string, sizeof(string), "virtualworld: %d", GetPlayerVirtualWorld(playerid));
	SendClientMessage(playerid, -1, string);
	return 1;
}
```
It can be fixed like this:
```Pawn
CMD:world(playerid, params[])
{
	SetPlayerVirtualWorld(playerid, strval(params));
	Streamer_ToggleItem(playerid, STREAMER_TYPE_PICKUP, test_pickup_id, false);
	SetTimerEx("test", 500, 0, "d", playerid);
	return 1;
}
forward test(playerid);
public test(playerid)
{
	Streamer_ToggleItem(playerid, STREAMER_TYPE_PICKUP, test_pickup_id, true);
}
```
Tested on `1.8.2`, `1.9.4`

### PR DESCRIPTION
**Pull request by ziggi**

### CODE REVIEW

File: src/streamer.cpp [hunk 1]
```diff
@@ -1063,17 +1063,23 @@ void Streamer::discoverPickups(Player &player, const std::vector<SharedCell> &ce
 	{
 		for (boost::unordered_map<int, Item::SharedPickup>::const_iterator p = (*c)->pickups.begin(); p != (*c)->pickups.end(); ++p)
 		{
+			if (p->second->worlds.empty())
+			{
+				p->second->worlds.insert(-1);
```
Comment (samp-incognito) [inline src/streamer.cpp]: I've not tested this, but I'm pretty sure that explicitly adding `-1` will interfere with the array data manipulation functions. An empty container is supposed signify that the pickup exists in all worlds.

Comment (ziggi) [reply src/streamer.cpp]: My bad, I shouldn't have changed it. Should be better now.
